<?php

namespace App\Services;

class SupplyInventoryCatalog
{
    /**
     * Get all 9 Inventory Types / Submodules with their groups.
     * All groups within every type are strictly continuous from 1 to N.
     */
    public static function getTypes(): array
    {
        return [
            1 => [
                'id' => 1,
                'name' => 'MATERIALES',
                'slug' => 'materiales',
                'description' => 'Insumos de construcción, plomería, eléctricos, químicos, aceros y ferretería general.',
                'icon' => 'Boxes',
                'color' => 'bg-blue-50 text-blue-600',
                'border' => 'border-blue-200',
                'hover' => 'hover:border-blue-500 hover:shadow-blue-100',
                'accent' => 'blue',
                'groups' => [
                    ['number' => 1, 'name' => 'ACCESORIOS', 'is_inventoried' => true],
                    ['number' => 2, 'name' => 'ACEROS', 'is_inventoried' => true],
                    ['number' => 3, 'name' => 'ADITIVOS', 'is_inventoried' => true],
                    ['number' => 4, 'name' => 'AGLUTINANTES', 'is_inventoried' => true],
                    ['number' => 5, 'name' => 'AGUA POTABLE', 'is_inventoried' => true],
                    ['number' => 6, 'name' => 'ALCANTARILLADO', 'is_inventoried' => true],
                    ['number' => 7, 'name' => 'CERRADURAS', 'is_inventoried' => true],
                    ['number' => 8, 'name' => 'COMBUSTIBLES', 'is_inventoried' => true],
                    ['number' => 9, 'name' => 'CONCRETOS', 'is_inventoried' => true],
                    ['number' => 10, 'name' => 'IMPERMEABILIZANTE', 'is_inventoried' => true],
                    ['number' => 11, 'name' => 'LIMPIEZA', 'is_inventoried' => true],
                    ['number' => 12, 'name' => 'LOSETAS', 'is_inventoried' => true],
                    ['number' => 13, 'name' => 'LLANTAS PARA EQUIPOS', 'is_inventoried' => true],
                    ['number' => 14, 'name' => 'MADERA', 'is_inventoried' => true],
                    ['number' => 15, 'name' => 'MATERIAL ELECTRICO', 'is_inventoried' => true],
                    ['number' => 16, 'name' => 'MATERIAL DE PLOMERIA', 'is_inventoried' => true],
                    ['number' => 17, 'name' => 'MUEBLES', 'is_inventoried' => true],
                    ['number' => 18, 'name' => 'PETREOS', 'is_inventoried' => true],
                    ['number' => 19, 'name' => 'PINTURAS', 'is_inventoried' => true],
                    ['number' => 20, 'name' => 'PREFABRICADOS', 'is_inventoried' => true],
                    ['number' => 21, 'name' => 'PUERTAS', 'is_inventoried' => true],
                    ['number' => 22, 'name' => 'SILICONES', 'is_inventoried' => true],
                    ['number' => 23, 'name' => 'TERRACERIAS', 'is_inventoried' => true],
                    ['number' => 24, 'name' => 'TORNILLERIA', 'is_inventoried' => true],
                    ['number' => 25, 'name' => 'VENTANAS', 'is_inventoried' => true],
                    ['number' => 26, 'name' => 'ACERO AL CARBON', 'is_inventoried' => true],
                    ['number' => 27, 'name' => 'FOFO', 'is_inventoried' => true],
                    ['number' => 28, 'name' => 'BOMBAS', 'is_inventoried' => true],
                    ['number' => 29, 'name' => 'ALUMINIO', 'is_inventoried' => true],
                    ['number' => 30, 'name' => 'RECARGAS', 'is_inventoried' => true],
                    ['number' => 31, 'name' => 'EQUIPO PARA LABORATORIO', 'is_inventoried' => true],
                    ['number' => 32, 'name' => 'PAPELERIA', 'is_inventoried' => true],
                    ['number' => 33, 'name' => 'LAMINAS', 'is_inventoried' => true],
                    ['number' => 34, 'name' => 'AIRE ACONDICIONADO', 'is_inventoried' => true],
                    ['number' => 35, 'name' => 'DUROCK', 'is_inventoried' => true],
                    ['number' => 36, 'name' => 'EMULSIONES ASFALTICAS', 'is_inventoried' => false],
                    ['number' => 37, 'name' => 'JARDINERIA', 'is_inventoried' => true],
                    ['number' => 38, 'name' => 'REDES DE VOZ Y DATOS', 'is_inventoried' => true],
                    ['number' => 39, 'name' => 'MATERIA PRIMA MERMELADA', 'is_inventoried' => true],
                    ['number' => 40, 'name' => 'REDES HIDRAULICA Y SANITARIA', 'is_inventoried' => false],
                    ['number' => 41, 'name' => 'ROTULOS', 'is_inventoried' => false],
                    ['number' => 42, 'name' => 'MOLDES', 'is_inventoried' => true],
                    ['number' => 43, 'name' => 'TRATAMIENTO DE AGUA', 'is_inventoried' => true],
                    ['number' => 44, 'name' => 'QUIMICOS', 'is_inventoried' => true],
                    ['number' => 45, 'name' => 'LIMONES', 'is_inventoried' => true],
                    ['number' => 46, 'name' => 'MATERIAL PARA RED DE GAS', 'is_inventoried' => true],
                    ['number' => 47, 'name' => 'BLANCOS', 'is_inventoried' => true],
                    ['number' => 48, 'name' => 'AGROPECUARIOS', 'is_inventoried' => true],
                    ['number' => 49, 'name' => 'SERIGRAFIA', 'is_inventoried' => true],
                    ['number' => 50, 'name' => 'PAYS', 'is_inventoried' => true],
                    ['number' => 51, 'name' => 'CONCRETO', 'is_inventoried' => true],
                    ['number' => 52, 'name' => 'PURIFICADORA DE AGUA', 'is_inventoried' => false],
                    ['number' => 53, 'name' => 'MATERIALES NOMINA', 'is_inventoried' => false],
                    ['number' => 54, 'name' => 'MORTEROS', 'is_inventoried' => true],
                ],
            ],
            2 => [
                'id' => 2,
                'name' => 'MANO DE OBRA',
                'slug' => 'mano-de-obra',
                'description' => 'Servicios, cuadrillas, albañilería, cimentación, acabados y mano de obra operativa.',
                'icon' => 'Users',
                'color' => 'bg-amber-50 text-amber-600',
                'border' => 'border-amber-200',
                'hover' => 'hover:border-amber-500 hover:shadow-amber-100',
                'accent' => 'amber',
                'groups' => [
                    ['number' => 1, 'name' => 'SALARIADO', 'is_inventoried' => false],
                    ['number' => 2, 'name' => 'CIMENTACION', 'is_inventoried' => false],
                    ['number' => 3, 'name' => 'EDIFICACION', 'is_inventoried' => false],
                    ['number' => 4, 'name' => 'ALBAÑILERIA', 'is_inventoried' => false],
                    ['number' => 5, 'name' => 'OBRAS EXTERIORES', 'is_inventoried' => false],
                    ['number' => 6, 'name' => 'URBANIZACION', 'is_inventoried' => false],
                    ['number' => 7, 'name' => 'CICLO DE AGUA', 'is_inventoried' => false],
                    ['number' => 8, 'name' => 'ELECTRIFICACION', 'is_inventoried' => false],
                    ['number' => 9, 'name' => 'ACABADOS', 'is_inventoried' => false],
                    ['number' => 10, 'name' => 'COSTOS INDIRECTOS DIRECTOS DE OBRA', 'is_inventoried' => false],
                    ['number' => 11, 'name' => 'JARDINERIA', 'is_inventoried' => false],
                    ['number' => 12, 'name' => 'LIMONES', 'is_inventoried' => true],
                    ['number' => 13, 'name' => 'ACTIVIDAD', 'is_inventoried' => false],
                    ['number' => 14, 'name' => 'MANO DE OBRA NOMINA', 'is_inventoried' => false],
                    ['number' => 15, 'name' => 'CUADRILLAS', 'is_inventoried' => true],
                ],
            ],
            3 => [
                'id' => 3,
                'name' => 'HERRAMIENTA Y EQUIPO',
                'slug' => 'herramienta-y-equipo',
                'description' => 'Herramientas menores, maquinaria, refacciones, cimbras, andamiajes y topografía.',
                'icon' => 'Wrench',
                'color' => 'bg-rose-50 text-rose-600',
                'border' => 'border-rose-200',
                'hover' => 'hover:border-rose-500 hover:shadow-rose-100',
                'accent' => 'rose',
                'groups' => [
                    ['number' => 1, 'name' => 'HERRAMIENTA MENOR', 'is_inventoried' => true],
                    ['number' => 2, 'name' => 'MAQUINARIA', 'is_inventoried' => true],
                    ['number' => 3, 'name' => 'REFACCIONES', 'is_inventoried' => true],
                    ['number' => 4, 'name' => 'CIMBRAS Y ANDAMIAJES', 'is_inventoried' => true],
                    ['number' => 5, 'name' => 'ARRENDAMIENTO DE CIMBRAS', 'is_inventoried' => false],
                    ['number' => 6, 'name' => 'EQUIPOS MECANICOS', 'is_inventoried' => true],
                    ['number' => 7, 'name' => 'EQUIPO PARA TOPOGRAFIA', 'is_inventoried' => true],
                    ['number' => 8, 'name' => 'LIMONES', 'is_inventoried' => true],
                    ['number' => 9, 'name' => 'HERRAMIENTA Y EQUIPO NOMINA', 'is_inventoried' => false],
                    ['number' => 10, 'name' => 'TIPOS DE MAQUINARIA', 'is_inventoried' => false],
                    ['number' => 11, 'name' => 'RENTAS MOLDES Y ANDAMIOS', 'is_inventoried' => false],
                ],
            ],
            4 => [
                'id' => 4,
                'name' => 'SUBCONTRATOS',
                'slug' => 'subcontratos',
                'description' => 'Servicios especializados de terceros, terracerías, renta de sanitarios y mantenimiento.',
                'icon' => 'FileSignature',
                'color' => 'bg-indigo-50 text-indigo-600',
                'border' => 'border-indigo-200',
                'hover' => 'hover:border-indigo-500 hover:shadow-indigo-100',
                'accent' => 'indigo',
                'groups' => [
                    ['number' => 1, 'name' => 'TERRACERIAS', 'is_inventoried' => false],
                    ['number' => 2, 'name' => 'ELECTRIFICACION', 'is_inventoried' => false],
                    ['number' => 3, 'name' => 'IMPERMEABILIZACION', 'is_inventoried' => false],
                    ['number' => 4, 'name' => 'TRABAJOS DE TALLER MECANICO', 'is_inventoried' => false],
                    ['number' => 5, 'name' => 'REDES HIDRAULICA Y SANITARIA', 'is_inventoried' => false],
                    ['number' => 6, 'name' => 'RENTA DE MAQUINARIA', 'is_inventoried' => false],
                    ['number' => 7, 'name' => 'RENTA DE SANITARIOS', 'is_inventoried' => false],
                    ['number' => 8, 'name' => 'OBRAS EXTERIORES', 'is_inventoried' => false],
                    ['number' => 9, 'name' => 'ACABADOS', 'is_inventoried' => false],
                    ['number' => 10, 'name' => 'CICLO DEL AGUA (PRESUPUESTOS)', 'is_inventoried' => false],
                    ['number' => 11, 'name' => 'ELECTRIFICACION (PRESUPUESTOS)', 'is_inventoried' => false],
                    ['number' => 12, 'name' => 'SERVICIO Y MANTENIMIENTO', 'is_inventoried' => false],
                    ['number' => 13, 'name' => 'OBRAS EXTERIORES', 'is_inventoried' => false],
                    ['number' => 14, 'name' => 'CICLO DEL AGUA DESCARGA', 'is_inventoried' => false],
                    ['number' => 15, 'name' => 'CICLO DEL AGUA', 'is_inventoried' => false],
                    ['number' => 16, 'name' => 'ELECTRIFICACION', 'is_inventoried' => false],
                    ['number' => 17, 'name' => 'PLANTA DE TRATAMIENTO DE AGUAS RESIDUALES', 'is_inventoried' => false],
                    ['number' => 18, 'name' => 'URBANIZACION', 'is_inventoried' => false],
                    ['number' => 19, 'name' => 'MOLDES', 'is_inventoried' => false],
                    ['number' => 20, 'name' => 'AGUA PURIFICADA', 'is_inventoried' => false],
                    ['number' => 21, 'name' => 'PERFORACION DE POZO PROFUNDO', 'is_inventoried' => false],
                    ['number' => 22, 'name' => 'TORRES QUETZALCOATL', 'is_inventoried' => false],
                    ['number' => 23, 'name' => 'LIMONES', 'is_inventoried' => false],
                    ['number' => 24, 'name' => 'NAVES INDUSTRIALES', 'is_inventoried' => false],
                    ['number' => 25, 'name' => 'SUBCONTRATOS NOMINA', 'is_inventoried' => false],
                    ['number' => 26, 'name' => 'RETENCIONES', 'is_inventoried' => false],
                    ['number' => 27, 'name' => 'ANTICIPOS', 'is_inventoried' => false],
                ],
            ],
            5 => [
                'id' => 5,
                'name' => 'INDIRECTOS',
                'slug' => 'indirectos',
                'description' => 'Maquinaria de soporte, depreciación, amortización, honorarios y gastos generales.',
                'icon' => 'PieChart',
                'color' => 'bg-purple-50 text-purple-600',
                'border' => 'border-purple-200',
                'hover' => 'hover:border-purple-500 hover:shadow-purple-100',
                'accent' => 'purple',
                'groups' => [
                    ['number' => 1, 'name' => 'MAQUINARIA', 'is_inventoried' => true],
                    ['number' => 2, 'name' => 'INDIRECTOS SUELDOS Y SALARIOS', 'is_inventoried' => false],
                    ['number' => 3, 'name' => 'INDIRECTOS DEPRECIACION', 'is_inventoried' => false],
                    ['number' => 4, 'name' => 'INDIRECTOS AMORTIZACION', 'is_inventoried' => false],
                    ['number' => 5, 'name' => 'HONORARIOS', 'is_inventoried' => false],
                    ['number' => 6, 'name' => 'ARRENDAMIENTOS', 'is_inventoried' => false],
                    ['number' => 7, 'name' => 'MANTENIMIENTO', 'is_inventoried' => false],
                    ['number' => 8, 'name' => 'GASTOS DE INDIRECTOS GENERALES', 'is_inventoried' => false],
                    ['number' => 9, 'name' => 'LIMONES', 'is_inventoried' => false],
                    ['number' => 10, 'name' => 'INDIRECTOS DIRECTOS DE OBRA', 'is_inventoried' => false],
                    ['number' => 11, 'name' => 'PROYECTO MERMELADAS', 'is_inventoried' => false],
                ],
            ],
            6 => [
                'id' => 6,
                'name' => 'ADMINISTRATIVOS',
                'slug' => 'administrativos',
                'description' => 'Equipo de cómputo, comunicaciones, mobiliario, oficina y gestión corporativa.',
                'icon' => 'Briefcase',
                'color' => 'bg-teal-50 text-teal-600',
                'border' => 'border-teal-200',
                'hover' => 'hover:border-teal-500 hover:shadow-teal-100',
                'accent' => 'teal',
                'groups' => [
                    ['number' => 1, 'name' => 'SUELDOS Y SALARIOS', 'is_inventoried' => false],
                    ['number' => 2, 'name' => 'DEPRECIACION', 'is_inventoried' => false],
                    ['number' => 3, 'name' => 'AMORTIZACION', 'is_inventoried' => false],
                    ['number' => 4, 'name' => 'HONORARIOS', 'is_inventoried' => false],
                    ['number' => 5, 'name' => 'ARRENDAMIENTOS', 'is_inventoried' => false],
                    ['number' => 6, 'name' => 'MANTENIMIENTO', 'is_inventoried' => false],
                    ['number' => 7, 'name' => 'GASTOS ADMINISTRATIVOS GENERALES', 'is_inventoried' => false],
                    ['number' => 8, 'name' => 'ACCESORIOS DE EQUIPO DE COMPUTO', 'is_inventoried' => false],
                    ['number' => 9, 'name' => 'ACCESORIOS Y EQUIPOS MENORES DE COMUNICACIONES', 'is_inventoried' => false],
                    ['number' => 10, 'name' => 'MOBILIARIOS Y EQUIPO DE OFICINA', 'is_inventoried' => false],
                    ['number' => 11, 'name' => 'LIMONES', 'is_inventoried' => false],
                    ['number' => 12, 'name' => 'ADMINISTRACION EXTERNA', 'is_inventoried' => false],
                ],
            ],
            7 => [
                'id' => 7,
                'name' => 'LICENCIAS, TRAMITES Y PERMISOS',
                'slug' => 'licencias-tramites-y-permisos',
                'description' => 'Terrenos, licencias, estudios, proyectos, créditos, titulación y entrega recepción.',
                'icon' => 'ScrollText',
                'color' => 'bg-orange-50 text-orange-600',
                'border' => 'border-orange-200',
                'hover' => 'hover:border-orange-500 hover:shadow-orange-100',
                'accent' => 'orange',
                'groups' => [
                    ['number' => 1, 'name' => 'TERRENOS', 'is_inventoried' => false],
                    ['number' => 2, 'name' => 'LICENCIAS Y PERMISOS', 'is_inventoried' => false],
                    ['number' => 3, 'name' => 'ESTUDIOS Y PROYECTOS', 'is_inventoried' => false],
                    ['number' => 4, 'name' => 'TITULACION', 'is_inventoried' => false],
                    ['number' => 5, 'name' => 'ADMINISTRACION EXTERNA', 'is_inventoried' => false],
                    ['number' => 6, 'name' => 'CONCRETERAS O SILOS', 'is_inventoried' => false],
                    ['number' => 7, 'name' => 'MAQUINARIA', 'is_inventoried' => false],
                    ['number' => 8, 'name' => 'CREDITO O MULTAS', 'is_inventoried' => false],
                    ['number' => 9, 'name' => 'ENTREGA RECEPCION', 'is_inventoried' => false],
                    ['number' => 10, 'name' => 'CICLO DEL AGUA', 'is_inventoried' => false],
                    ['number' => 11, 'name' => 'LIMONES', 'is_inventoried' => false],
                ],
            ],
            8 => [
                'id' => 8,
                'name' => 'BASICOS',
                'slug' => 'basicos',
                'description' => 'Alcantarillado básico, actividades generales y suministros base de obra.',
                'icon' => 'Layers',
                'color' => 'bg-cyan-50 text-cyan-600',
                'border' => 'border-cyan-200',
                'hover' => 'hover:border-cyan-500 hover:shadow-cyan-100',
                'accent' => 'cyan',
                'groups' => [
                    ['number' => 1, 'name' => 'ALCANTARILLADO', 'is_inventoried' => true],
                    ['number' => 2, 'name' => 'BASICOS DE OBRA', 'is_inventoried' => false],
                    ['number' => 3, 'name' => 'LIMONES', 'is_inventoried' => false],
                    ['number' => 4, 'name' => 'ACTIVIDAD', 'is_inventoried' => false],
                ],
            ],
            9 => [
                'id' => 9,
                'name' => 'COMERCIALIZACION',
                'slug' => 'comercializacion',
                'description' => 'Insumos de ventas, distribución, comercialización, mantenimiento y administración.',
                'icon' => 'ShoppingBag',
                'color' => 'bg-emerald-50 text-emerald-600',
                'border' => 'border-emerald-200',
                'hover' => 'hover:border-emerald-500 hover:shadow-emerald-100',
                'accent' => 'emerald',
                'groups' => [
                    ['number' => 1, 'name' => 'SUELDOS Y SALARIOS', 'is_inventoried' => false],
                    ['number' => 2, 'name' => 'DEPRECIACION', 'is_inventoried' => false],
                    ['number' => 3, 'name' => 'AMORTIZACION', 'is_inventoried' => false],
                    ['number' => 4, 'name' => 'HONORARIOS', 'is_inventoried' => false],
                    ['number' => 5, 'name' => 'ARRENDAMIENTOS', 'is_inventoried' => false],
                    ['number' => 6, 'name' => 'MANTENIMIENTO', 'is_inventoried' => false],
                    ['number' => 7, 'name' => 'GASTOS ADMINISTRATIVOS GENERALES', 'is_inventoried' => false],
                    ['number' => 8, 'name' => 'LIMONES', 'is_inventoried' => false],
                ],
            ],
        ];
    }

    /**
     * Find type by ID or slug.
     */
    public static function findType($identifier): ?array
    {
        $types = self::getTypes();
        if (is_numeric($identifier) && isset($types[(int)$identifier])) {
            return $types[(int)$identifier];
        }

        foreach ($types as $type) {
            if ($type['slug'] === $identifier) {
                return $type;
            }
        }

        return null;
    }
}
